---
title: "RFoose_Final_DataProj_2020"
output: html_document
---

```{r}
#The goal of this data project is to compare opioid pills sent to geographical attendance areas of both high and low performing school districts in Maryland and to compare student outcomes -- performance of math and reading on fourth grade students.  A second analysis will be to introudce teacher level experience for each school in the geographical area to determine if the level (years of experience and degree 'bachelor or masters').  The latter analysis would be a first glance review for deeper analysis potentially in a different study. 

```




```{r}

# Load Tidyverse, Janitor and arcos
library(tidyverse)
library(janitor)
library(arcos)

```

```{r}

# store the API key as an object called key - as a way to access opioid database
key <- "uO4EK6I"

```


```{r}

arcos_county_pills_per_year <- summarized_county_annual(key = key) %>%
  clean_names()
#accessing all data of all pills from in each county

```


```{r}
baltimore_city_pills_per_year <- arcos_county_pills_per_year %>%
  filter(buyer_state == "MD", buyer_county == "BALTIMORE CITY") %>%
  select(year, dosage_unit)
#pulling out the pills sent to Baltimore City

```


```{r}
#from here I will model what we learned in class to build out this graph before adding the other counties.

```


```{r}
  ggplot(baltimore_city_pills_per_year) +
  geom_line(stat="identity", aes(year, dosage_unit))

```



```{r}
  options(scipen=999)
 
  ggplot(baltimore_city_pills_per_year) +
  geom_bar(stat="identity", aes(year, dosage_unit))

```



```{r}
  ggplot(baltimore_city_pills_per_year) +
  geom_bar(stat="identity", aes(year, dosage_unit), fill="royal blue") 
  
```


```{r}
  ggplot(baltimore_city_pills_per_year) +
  geom_bar(stat="identity", aes(year, dosage_unit), fill="royal blue") +
  labs(x="Year", y="Total pills") 
  
```



```{r}
  ggplot(baltimore_city_pills_per_year) +
  geom_bar(stat="identity", aes(year, dosage_unit), fill="royal blue") +
  labs(x="Year", y="Total pills", title="In Baltimore City, opioids fall in 2007, then climb steadily through 2012", subtitle = "Total pills shipped to Baltimore City by year", caption = "Source: DEA ARCOS database, via Washington Post")

```


```{r}
  ggplot(baltimore_city_pills_per_year) +
  geom_bar(stat="identity", aes(year, dosage_unit), fill="royal blue") +
  labs(x="Year", y="Total pills", title="In Baltimore City, opioids fall in 2007, then climb steadily through 2012", subtitle = "Total pills shipped to Baltimore City by year", caption = "Source: DEA ARCOS database, via Washington Post") +
  scale_x_continuous(breaks = c(2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016)) 

```


```{r}
#install.packages('scales') 
# You must install scales for this to work
 library(scales)

  ggplot(baltimore_city_pills_per_year) +
  geom_bar(stat="identity", aes(year, dosage_unit), fill="royal blue") +
  labs(x="Year", y="Total pills", title="In Baltimore City, opioids fall in 2007, then climb steadily through 2012", subtitle = "Total pills shipped to Baltimore City by year", caption = "Source: DEA ARCOS database, via Washington Post") +
  scale_x_continuous(breaks = c(2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016)) +
  scale_y_continuous(labels = comma)
```

```{r}

  ggplot(baltimore_city_pills_per_year) +
  geom_bar(stat="identity", aes(year, dosage_unit), fill="royal blue") +
  labs(x="Year", y="Total pills", title="In Baltimore City, opioids fall in 2007, then climb steadily through 2012", subtitle = "Total pills shipped to Baltimore City by year", caption = "Source: DEA ARCOS database, via Washington Post") +
  scale_x_continuous(breaks = c(2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016)) +
  scale_y_continuous(labels = comma)
  ggsave("baltimore_pills.png", plot=last_plot())
```


```{r}
#adding the rest of the other counties that are large - collectively called "the big 8" in education circles in Md
maryland_pills_per_year <- arcos_county_pills_per_year %>%
  filter(buyer_state == "MD", (buyer_county %in% c("ANNE ARUNDEL", "BALTIMORE CITY", "BALTIMORE", "HOWARD","MONTGOMERY", "PRINCE GEORGES"))) %>%
  select(buyer_county, year, dosage_unit)
```


```{r}
  ggplot(maryland_pills_per_year) +
  geom_bar(stat="identity", aes(year, dosage_unit), fill="royal blue") +
  labs(x="Year", y="Total pills", title="Steady rise in opioids in six large Maryland counties", subtitle = "Total pills per year shipped to Anne Arundel, Baltimore, Howard,\nMontgomery, Prince George's counties and Baltimore City", caption = "Source: DEA ARCOS database, via Washington Post") +
  scale_x_continuous(breaks = c(2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016)) +
  scale_y_continuous(labels = comma)
  
```


```{r}
  ggplot(maryland_pills_per_year) +
  geom_bar(stat="identity", aes(year, dosage_unit), fill="royal blue") +
  labs(x="Year", y="Total pills", title="Steady rise in opioids in six large Maryland counties", subtitle = "Total pills per year shipped to Anne Arundel, Baltimore, Howard,\nMontgomery, Prince George's counties and Baltimore City", caption = "Source: DEA ARCOS database, via Washington Post") +
  scale_x_continuous(breaks = c(2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,2015,2016)) +
  scale_y_continuous(labels = comma)
  
```

```{r}
  ggplot(maryland_pills_per_year) +
  geom_bar(stat="identity", aes(year, dosage_unit, fill=buyer_county)) +
  labs(x="Year", y="Total pills", title="Steady rise in opioids in six large Maryland counties", subtitle = "Total pills per year shipped to Anne Arundel, Baltimore, Howard,\nMontgomery, Prince George's counties and Baltimore City", caption = "Source: DEA ARCOS database, via Washington Post", fill="County") +
  scale_x_continuous(breaks = c(2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016)) +
  scale_y_continuous(labels = comma)
  
```


```{r}
  ggplot(maryland_pills_per_year) +
  geom_bar(stat="identity", aes(year, dosage_unit, fill=buyer_county)) +
  labs(x="Year", y="Total pills", title="Steady rise in opioids in six large Maryland counties", subtitle = "Total pills per year shipped to Anne Arundel, Baltimore, Howard,\nMontgomery, Prince George's counties and Baltimore City", caption = "Source: DEA ARCOS database, via Washington Post", fill="County") +
  scale_x_continuous(breaks = c(2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016)) +
  scale_y_continuous(labels = comma) +
  facet_wrap(nrow=2, . ~ buyer_county)
  
```


```{r}
  ggplot(maryland_pills_per_year) +
  geom_bar(stat="identity", aes(year, dosage_unit, fill=buyer_county)) +
  labs(x="Year", y="Total pills", title="Steady rise in opioids in six large Maryland counties", subtitle = "Total pills per year shipped to Anne Arundel, Baltimore, Howard,\nMontgomery, Prince George's counties and Baltimore City", caption = "Source: DEA ARCOS database, via Washington Post", fill="County") +
  scale_x_continuous(breaks = c(2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014)) +
  scale_y_continuous(labels = comma) +
  facet_wrap(nrow=2, . ~ buyer_county) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
```


```{r}

maryland_pills_2012 <- arcos_county_pills_per_year %>%
  filter(buyer_state == "MD", year=="2012") %>%
  select(buyer_county, year, dosage_unit)
```


```{r}
maryland_2012 <- maryland_pills_2012 %>%
  inner_join(maryland_population_2012, by=("buyer_county")) %>%
  select(buyer_county, dosage_unit, population)

```


```{r}

ggplot(maryland_2012) +
  geom_point(aes(population, dosage_unit))

```


```{r}

ggplot(maryland_2012) +
  geom_point(aes(population, dosage_unit)) +
  labs(x="2012 Population", y="Total pills in 2012", title="Maryland county population and total opioids in 2012", caption = "Source: DEA ARCOS database, via Washington Post", fill="buyer_county") +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(labels = comma) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


```{r}

ggplot(maryland_2012) +
  geom_point(aes(population, dosage_unit)) +
  labs(x="2012 Population", y="Total pills in 2012", title="County population and total opioids in 2012", caption = "Source: DEA ARCOS database, via Washington Post", fill="buyer_county") +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(labels = comma) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_smooth(aes(population, dosage_unit), method = "lm", se = FALSE)


  
```



```{r}
# install.packages('ggrepel')
library(ggrepel)

ggplot(maryland_2012) +
  geom_point(aes(population, dosage_unit)) +
  labs(x="2012 Population", y="Total pills in 2012", title="County population and total opioids in 2012", caption = "Source: DEA ARCOS database, via Washington Post", fill="buyer_county") +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(labels = comma) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_smooth(aes(population, dosage_unit), method = "lm", se = FALSE) +
  geom_text_repel(aes(population, dosage_unit, label=buyer_county))

```


```{r}

ggplot(maryland_2012) +
  geom_point(aes(population, dosage_unit)) +
  labs(x="2012 Population", y="Total pills in 2012", title="Maryland county population and total opioids in 2012", caption = "Source: DEA ARCOS database, via Washington Post", fill="buyer_county") +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(labels = comma) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_smooth(aes(population, dosage_unit), method = "lm", se = FALSE) +
  geom_text_repel(aes(population, dosage_unit, label=buyer_county),
                  subset(maryland_2012, population > 175000))

```


```{r}

ggplot(maryland_2012) +
  geom_point(aes(population, dosage_unit)) +
  labs(x="2012 Population", y="Total pills in 2012", title="Baltimore County, Baltimore City, Anne Arundel County \nhad high number of opioids relative to population in 2012", caption = "Source: DEA ARCOS database, via Washington Post", fill="buyer_county") +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(labels = comma) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_smooth(aes(population, dosage_unit), method = "lm", se = FALSE) +
  geom_text_repel(aes(population, dosage_unit, label=buyer_county),
                  subset(maryland_2012, population > 175000))

```

```{r}

# Now I want to add in the education data - BUT this is a source of frustration.  I am not sure how to exactly flush this out.... I would like to sit in class and work with Sean.  I may be doing too much and need to focus my question more directly.  

```


```{r}
#import this package to open xlsx files
library(openxlsx)

#load our relevant files
file1 = read.csv("file 1.csv")
file2 = read.csv("file2.csv")
file3 = read.xlsx("File 3.xlsx")

```
```{r}
#checking glimpse of the file before making changes
#glimpse(file1)


file1 = file1 %>%
  clean_names() %>%
  filter(lss_name == c("Howard", "Montgomery", "Prince George's", "Baltimore County", "Baltimore City", "Anne Arundel")) %>%
  group_by(assessment, lss_name) %>%
#  select(lss_name, assessment, grade) %>%
  arrange(desc(assessment))

```
```{r}

glimpse(file3)

file3 = file3 %>%
  clean_names() %>%
  mutate(years_experience_yym = as.numeric(years_experience_yym)) %>%
  filter(lss_name == c("Howard", "Montgomery", "Prince George's", "Baltimore County", "Baltimore City", "Anne Arundel")) %>%
  arrange(years_experience_yym)

```

